### ISSUE TITLE
Errors building on Windows

### ISSUE THREAD

**Issue by mattjohnsonpint** [bigeasy/timezone#137]
I can't seem to build this.  I am getting:

```
make: *** No rule to make target `build/olson/africa.js', needed by `build/timezone/America/Detroit.js'.  Stop.
```

I am running on Windows with MinGW and NodeJS.  Could that be part of the problem?  The rest of the build seems to work without issue.

Question - Why is detroit called out in the makefile?  And how could that be related to africa?

Thanks.

**Comment by bcaller** [comment]
Followed the advice to get it to work with cygwin:

Clone timezone
Clone tz into ```./eggert``` directory and make
Run this from your timezone directory:
```
cd eggert/tz
make
cd ../../ #root timezone
make
cp -R build/timezone node_modules # copy to node_modules so tests work (HACKY)
npm install
for i in t/*/*.js; do node $i; done # run tests
```
The npm test command doesn't appear to work, just run the *.t.js files in the t directory with node.

**Comment by bigeasy** [comment]
If you have suggestions on how to get it to build on Windows I will take them. Note that you don't need to build on Windows to run on Windows. The build compares the Timezone output to the output of Ruby when using `tzdata` files compiled from the most recent IANA database.
