### ISSUE TITLE
Leap second

### ISSUE THREAD

**Issue by sberryman** [bigeasy/timezone#228]
So I just read the article mentioning the leap second that is going to occur on June 30th and would like to be a little proactive this time around as time is the most important aspect of my app.

I've never had an issue using your library but I was wondering if you had any suggestions on how to test this.

Here is a link to the article: http://www.usatoday.com/story/news/world/2015/01/08/computer-chaos-feares/21433363/

**Comment by bigeasy** [comment]
I'll write a test. Offhand, it doesn't appear that the `strftime` implementation is going to fail, but I don't know that it is going to exactly what C `strftime` is going to do. RFC 3999 has clear instructions on how to handle leap seconds. The tests for this ought to be simple. Simply see if the POSIX time for the leap second is formatted correctly for a few different timezones, then see if the RFC 3999 parser can parse a leap second date string.

Note that the knowledge of leap seconds is going to come out of the JavaScript implementation itself.

But, yes, this does raise questions. I'll have to look into it. Usually it means writing a couple examples programs in C, Java and Ruby to see how other developers have decided to handle the issue.

**Comment by bigeasy** [comment]
I created a test and was disappointed with the results. Then poked around to find that JavaScript ignores leap seconds. It's official.

http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.1

The `timezone` library will parse a date string with `60` for the seconds value, but it will not format it that way since it depends on `Date.getUTCSeconds` to determine the seconds.

What effect this has on an application, I'm not sure. I'm going to look to see what people say you're supposed to do about this.

**Comment by bigeasy** [comment]
@sberryman How is the absence of the leap second going to affect your application? Do you do date math in seconds across days? Or do you schedule events down to the second? Curious. If you've already found a solution, I'd be really interested to hear it.

**Comment by sberryman** [comment]
@bigeasy I was on vacation so sorry for the late reply. I don't really do anything down to the second level fortunately. Everything on my end is on the minute level and I haven't noticed any issues.

**Comment by bigeasy** [comment]
https://xkcd.com/1514/

**Comment by bigeasy** [comment]
@sberryman So, unless you have a process that will fail if it takes a second longer, then you shouldn't have any more of a problem with this timezone library than will most other applications that use POSIX time. The operating system is going to stay on the leap second for two seconds. That is how it handles it.

I suppose I could test this in a Docker container. Hey, I'll test this in a Docker container.

**Comment by bigeasy** [comment]
We seem to have survived the leap second. Thank you @sberryman for your attention to this matter.
