### ISSUE TITLE
timezone fails one test under Node 4

### ISSUE THREAD

**Issue by vielmetti** [bigeasy/timezone#239]
Tested under Travis with Node 4. The test suite passes every test except t/format/week-iso.t.js, where it produces the following error. The job run is at https://travis-ci.org/bigeasy/timezone/jobs/81085428 . Based on the error message, I think it's necessary to test `cadence` as well. I don't know if this is a failure in `proof` the test suite, or in the `timezone` code itself.

```
> ✘ t/format/week-iso.t.js: Bail Out!
# TypeError: step is not a function
#     at Object.<anonymous> (/home/travis/build/bigeasy/timezone/node_modules/proof/index.js:107:50)
#     at Object.invoke (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:425:43)
#     at /home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:260:26
#     at Object.starter (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:172:52)
#     at /home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:280:56
#     at Array.forEach (native)
#     at Object.<anonymous> (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:279:37)
#     at Object.invoke (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:439:14)
#     at Object.<anonymous> (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:285:24)
#     at Object.invoke (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:439:14)
> ✘ t/format/week-iso.t.js: exited with code 1
```

**Comment by bigeasy** [comment]
Timezone uses a much older version of Proof and Cadence. It needs to be upgraded to use the latest Proof and Cadence. We'll see if there are still problems after an upgrade.

**Comment by vielmetti** [comment]
This build succeeded

https://travis-ci.org/vielmetti/timezone/builds/81239406

under Node 4.0 and 4.1. The patch is https://github.com/bigeasy/timezone/commit/a362b762a9c8d030bb0efedf1f75d3b14f98c27c .

I still need to figure out rebase (what to type, and what it actually does).

**Comment by bigeasy** [comment]
Would you like to screen share?

**Comment by vielmetti** [comment]
Yes at some point.

**Comment by bigeasy** [comment]
Building under Node.js 4 these days.
