### ISSUE TITLE
Bundle files in npm package

### ISSUE THREAD

**Issue by pluma** [bigeasy/timezone#259]
The library as published on npm currently needs to access the filesystem to load the timezone files dynamically. It would simplify the library significantly if the list was instead hardcoded at publish time. This would allow using the library in environments where filesystem access is not available.

**Comment by bigeasy** [comment]
Browserify?

**Comment by pluma** [comment]
Including browserify/webpack, yes. But in my case I'm using the library on the server with [ArangoDB](https://www.arangodb.com/) which provides a V8-based but not fully node-compatible (e.g. non-async) JavaScript environment. I had to patch the two files to use different environment-specific APIs but I think it'd be cleaner if it just knew its require calls in advance.

**Comment by bigeasy** [comment]
I see what you mean. That loop. The programmer I am today would not do that. Will fix.

**Comment by bigeasy** [comment]
Sorry for the delay.

**Comment by bigeasy** [comment]
Available in 0.0.48. Thank you.
