### ISSUE TITLE
Make fails with error about build/olson/africa.js

### ISSUE THREAD

**Issue by yesthatguy** [bigeasy/timezone#263]
I just downloaded the latest .zip from GitHub and tried to run Make. It fails with the following error:

make: *** No rule to make target \`build/olson/africa.js', needed by \`build/timezone/America/Detroit.js'.  Stop.

Full Make output:
$ make
mkdir -p build/timezone
cp package.json build/timezone/package.json
mkdir -p build/timezone
cp README.md build/timezone/README.md
mkdir -p build/timezone
cp CHANGELOG build/timezone/CHANGELOG
mkdir -p build/timezone
cp src/synopsis.js build/timezone/synopsis.js
mkdir -p build/timezone
cp src/rfc822.js build/timezone/rfc822.js
mkdir -p build/timezone
cp src/loaded.js build/timezone/loaded.js
mkdir -p build/timezone
cp src/.npmignore build/timezone/.npmignore
mkdir -p build/timezone
cp src/locales/af_ZA.js build/timezone/af_ZA.js
mkdir -p build/timezone
cp src/locales/am_ET.js build/timezone/am_ET.js
mkdir -p build/timezone
cp src/locales/ast_ES.js build/timezone/ast_ES.js
mkdir -p build/timezone
cp src/locales/bg_BG.js build/timezone/bg_BG.js
mkdir -p build/timezone
cp src/locales/bn_BD.js build/timezone/bn_BD.js
mkdir -p build/timezone
cp src/locales/bn_IN.js build/timezone/bn_IN.js
mkdir -p build/timezone
cp src/locales/ca_ES.js build/timezone/ca_ES.js
mkdir -p build/timezone
cp src/locales/cs_CZ.js build/timezone/cs_CZ.js
mkdir -p build/timezone
cp src/locales/de_AT.js build/timezone/de_AT.js
mkdir -p build/timezone
cp src/locales/de_CH.js build/timezone/de_CH.js
mkdir -p build/timezone
cp src/locales/de_DE.js build/timezone/de_DE.js
mkdir -p build/timezone
cp src/locales/el_GR.js build/timezone/el_GR.js
mkdir -p build/timezone
cp src/locales/en_AU.js build/timezone/en_AU.js
mkdir -p build/timezone
cp src/locales/en_CA.js build/timezone/en_CA.js
mkdir -p build/timezone
cp src/locales/en_GB.js build/timezone/en_GB.js
mkdir -p build/timezone
cp src/locales/en_HK.js build/timezone/en_HK.js
mkdir -p build/timezone
cp src/locales/en_NZ.js build/timezone/en_NZ.js
mkdir -p build/timezone
cp src/locales/en_US.js build/timezone/en_US.js
mkdir -p build/timezone
cp src/locales/es_AR.js build/timezone/es_AR.js
mkdir -p build/timezone
cp src/locales/es_CL.js build/timezone/es_CL.js
mkdir -p build/timezone
cp src/locales/es_CO.js build/timezone/es_CO.js
mkdir -p build/timezone
cp src/locales/es_CR.js build/timezone/es_CR.js
mkdir -p build/timezone
cp src/locales/es_DO.js build/timezone/es_DO.js
mkdir -p build/timezone
cp src/locales/es_EC.js build/timezone/es_EC.js
mkdir -p build/timezone
cp src/locales/es_ES.js build/timezone/es_ES.js
mkdir -p build/timezone
cp src/locales/es_GT.js build/timezone/es_GT.js
mkdir -p build/timezone
cp src/locales/es_HN.js build/timezone/es_HN.js
mkdir -p build/timezone
cp src/locales/es_MX.js build/timezone/es_MX.js
mkdir -p build/timezone
cp src/locales/es_NI.js build/timezone/es_NI.js
mkdir -p build/timezone
cp src/locales/es_PA.js build/timezone/es_PA.js
mkdir -p build/timezone
cp src/locales/es_PE.js build/timezone/es_PE.js
mkdir -p build/timezone
cp src/locales/es_PR.js build/timezone/es_PR.js
mkdir -p build/timezone
cp src/locales/es_SV.js build/timezone/es_SV.js
mkdir -p build/timezone
cp src/locales/es_UY.js build/timezone/es_UY.js
mkdir -p build/timezone
cp src/locales/es_VE.js build/timezone/es_VE.js
mkdir -p build/timezone
cp src/locales/eu_ES.js build/timezone/eu_ES.js
mkdir -p build/timezone
cp src/locales/fi_FI.js build/timezone/fi_FI.js
mkdir -p build/timezone
cp src/locales/fr_BE.js build/timezone/fr_BE.js
mkdir -p build/timezone
cp src/locales/fr_CA.js build/timezone/fr_CA.js
mkdir -p build/timezone
cp src/locales/fr_CH.js build/timezone/fr_CH.js
mkdir -p build/timezone
cp src/locales/fr_FR.js build/timezone/fr_FR.js
mkdir -p build/timezone
cp src/locales/gl_ES.js build/timezone/gl_ES.js
mkdir -p build/timezone
cp src/locales/he_IL.js build/timezone/he_IL.js
mkdir -p build/timezone
cp src/locales/hi_IN.js build/timezone/hi_IN.js
mkdir -p build/timezone
cp src/locales/hr_HR.js build/timezone/hr_HR.js
mkdir -p build/timezone
cp src/locales/hu_HU.js build/timezone/hu_HU.js
mkdir -p build/timezone
cp src/locales/id_ID.js build/timezone/id_ID.js
mkdir -p build/timezone
cp src/locales/it_CH.js build/timezone/it_CH.js
mkdir -p build/timezone
cp src/locales/it_IT.js build/timezone/it_IT.js
mkdir -p build/timezone
cp src/locales/ja_JP.js build/timezone/ja_JP.js
mkdir -p build/timezone
cp src/locales/ko_KR.js build/timezone/ko_KR.js
mkdir -p build/timezone
cp src/locales/lt_LT.js build/timezone/lt_LT.js
mkdir -p build/timezone
cp src/locales/lv_LV.js build/timezone/lv_LV.js
mkdir -p build/timezone
cp src/locales/ms_MY.js build/timezone/ms_MY.js
mkdir -p build/timezone
cp src/locales/nb_NO.js build/timezone/nb_NO.js
mkdir -p build/timezone
cp src/locales/nds_DE.js build/timezone/nds_DE.js
mkdir -p build/timezone
cp src/locales/nl_BE.js build/timezone/nl_BE.js
mkdir -p build/timezone
cp src/locales/nl_NL.js build/timezone/nl_NL.js
mkdir -p build/timezone
cp src/locales/pl_PL.js build/timezone/pl_PL.js
mkdir -p build/timezone
cp src/locales/pt_BR.js build/timezone/pt_BR.js
mkdir -p build/timezone
cp src/locales/pt_PT.js build/timezone/pt_PT.js
mkdir -p build/timezone
cp src/locales/ru_RU.js build/timezone/ru_RU.js
mkdir -p build/timezone
cp src/locales/si_LK.js build/timezone/si_LK.js
mkdir -p build/timezone
cp src/locales/sl_SI.js build/timezone/sl_SI.js
mkdir -p build/timezone
cp src/locales/sq_AL.js build/timezone/sq_AL.js
mkdir -p build/timezone
cp src/locales/sr_RS.js build/timezone/sr_RS.js
mkdir -p build/timezone
cp src/locales/sv_SE.js build/timezone/sv_SE.js
mkdir -p build/timezone
cp src/locales/ta_IN.js build/timezone/ta_IN.js
mkdir -p build/timezone
cp src/locales/uk_UA.js build/timezone/uk_UA.js
mkdir -p build/timezone
cp src/locales/ur_PK.js build/timezone/ur_PK.js
mkdir -p build/timezone
cp src/locales/vi_VN.js build/timezone/vi_VN.js
mkdir -p build/timezone
cp src/locales/zh_CN.js build/timezone/zh_CN.js
mkdir -p build/timezone
cp src/locales/zh_HK.js build/timezone/zh_HK.js
mkdir -p build/timezone
cp src/locales/zh_TW.js build/timezone/zh_TW.js
mkdir -p build/timezone
cp src/timezone.js build/timezone/index.js
make: *** No rule to make target \`build/olson/africa.js', needed by \`build/timezone/America/Detroit.js'.  Stop.

**Comment by bigeasy** [comment]
The zipped release is a by-product. The zipped data releases contain the JSON format timezone data, but the other releases, they are by-products of tagging. Install the library via NPM or just used `timezone.js` on it's own.
