### ISSUE TITLE
Passing in date array warps the *input* in nasty ways

### ISSUE THREAD

**Issue by savvopoulos** [bigeasy/timezone#276]
```
> tz=require('timezone/loaded')
[Function]
> a = [2016, 11, 18]
[ 2016, 11, 18 ]
> tz(a)
1479427200000
> a
[ 2016, 10, 18, 0, 0, 0, 0, 0, 0, 0, 0 ]
```

Note that a[1] changes from 11 to 10, and, also, zeros are added.

**Comment by bigeasy** [comment]
Oooh, that's no good.

**Comment by savvopoulos** [comment]
No it's really bad and unacceptable, in an otherwise very well-thought out library!
Any chance you can fix it?
