### ISSUE TITLE
Internet or not ? For IANA database.

### ISSUE THREAD

**Issue by marcdubois71450** [bigeasy/timezone#322]
Hello, I would like to know if this library needs the Internet connection to work? Or if the IANA base is local?

I am not finding any information in the readme
Thank you for your reply.

**Comment by marcdubois71450** [comment]
And if it is local, in 2050 it still works without update?
And if it is online, is there any way you can pass requests through an HTTP proxy?


Thank you to guide me I must manage log between different time zone, and this machine is not connected to the internet for security reasons.

**Comment by bigeasy** [comment]
Database is local. You could load it as needed if you'd like from the browser, but for Node.js the database installs as part installing `timezone`.

**Comment by marcdubois71450** [comment]
Thank you very much for your response!
